#ifndef FILLRATENOMNOMNOM_CONSTANTS_H
#define FILLRATENOMNOMNOM_CONSTANTS_H

const int NUM_PARTICLES = 2000;
const bool CLEAR_FRAMEBUFFER = true;
const bool PERFORM_SORT = false;

#endif // FILLRATENOMNOMNOM_CONSTANTS_H
