#ifndef OCULUS_CONSTANTS_H
#define OCULUS_CONSTANTS_H

const int NUM_SEGMENTS = 200;
const float MAX_ROTATION_SPEED = 0.001f;
const float MIN_SEGMENT_LENGTH = 0.1f;
const float MAX_SEGMENT_LENGTH = 1;
const int CURVE_FIDELITY = 10;

#endif // OCULUS_CONSTANTS_H
