#ifndef STRAWBERRYFIELDSFOREVER_CONSTANTS_H
#define STRAWBERRYFIELDSFOREVER_CONSTANTS_H

const int FIELD_SIZE = 128;
const float NORMAL_MODIFIER = 25.0f;
const float OFFSET_MODIFIER = 10.0f;
const int NUM_NOISES = 4;

#endif // STRAWBERRYFIELDSFOREVER_CONSTANTS_H
