#ifndef VERYATTRACTIVE_CONSTANTS_H
#define VERYATTRACTIVE_CONSTANTS_H

const int ITERATIONS = 1000000;
const float CAMERA_SPEED = 0.0005f;
const float CHAOS = 0.25f;

#endif // VERYATTRACTIVE_CONSTANTS_H
